/*create table SUBSCRIPTION (id_subscription bigint generated by default as identity, birth varchar(255), email varchar(255), first_name varchar(255), gender varchar(255), news_letter_id varchar(255), newsletter boolean, primary key (id_subscription))
*/
INSERT INTO SUBSCRIPTION
(ID_SUBSCRIPTION,BIRTH,EMAIL,FIRST_NAME,GENDER,NEWS_LETTER_ID,NEWSLETTER)
VALUES
    (2, '20200212','test@gmail.com','tes','male','A1',true)
